INSERT INTO TB_ATIVIDADE (NOME, DESCRICAO, PRECO) VALUES ('Curso de HTML', 'Aprenda HTML de forma prática', 80.00);
INSERT INTO TB_ATIVIDADE (NOME, DESCRICAO, PRECO) VALUES ('Oficina de Github', 'Controle versões de seus projetos', 50.00);

INSERT INTO TB_BLOCO (INICIO, FIM, ATIVIDADE_ID) VALUES ('2017-09-25T08:00:00Z', '2017-09-25T11:00:00Z', 1);
INSERT INTO TB_BLOCO (INICIO, FIM, ATIVIDADE_ID) VALUES ('2017-09-25T14:00:00Z', '2017-09-25T18:00:00Z', 2);
INSERT INTO TB_BLOCO (INICIO, FIM, ATIVIDADE_ID) VALUES ('2017-09-26T08:00:00Z', '2017-09-26T11:00:00Z', 2);

INSERT INTO TB_CATEGORIA (DESCRICAO, ATIVIDADE_ID) VALUES ('Curso', 1);
INSERT INTO TB_CATEGORIA (DESCRICAO, ATIVIDADE_ID) VALUES ('Oficina', 2);

INSERT INTO TB_PARTICIPANTE (NOME, EMAIL) VALUES ('José Silva', 'jose@gmail.com');
INSERT INTO TB_PARTICIPANTE (NOME, EMAIL) VALUES ('Tiago Faria', 'tiago@gmail.com');
INSERT INTO TB_PARTICIPANTE (NOME, EMAIL) VALUES ('Maria do Rosário', 'maria@gmail.com');
INSERT INTO TB_PARTICIPANTE (NOME, EMAIL) VALUES ('Teresa Silva', 'teresa@gmail.com');

INSERT INTO TB_PARTICIPANTE_ATIVIDADE (PARTICIPANTE_ID, ATIVIDADE_ID) VALUES (1, 1);
INSERT INTO TB_PARTICIPANTE_ATIVIDADE (PARTICIPANTE_ID, ATIVIDADE_ID) VALUES (2, 1);
INSERT INTO TB_PARTICIPANTE_ATIVIDADE (PARTICIPANTE_ID, ATIVIDADE_ID) VALUES (3, 1);
INSERT INTO TB_PARTICIPANTE_ATIVIDADE (PARTICIPANTE_ID, ATIVIDADE_ID) VALUES (3, 2);
INSERT INTO TB_PARTICIPANTE_ATIVIDADE (PARTICIPANTE_ID, ATIVIDADE_ID) VALUES (4, 2);
